# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-02 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restshop', '0029_auto_20171123_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyvalue',
            name='property',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='value_set',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='PropertyValue',
        ),
    ]
